apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: express-api-prod

resources:
  - ../../base
  - ingress.yaml
  - certificate.yaml

labels:
  - pairs:
      environment: prod
    includeSelectors: false

images:
  - name: express-api
    newName: REPLACE_ECR_REGISTRY/express-api
    newTag: "1.0.0"

replicas:
  - name: express-api
    count: 3

patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment
      name: express-api
  - path: patches/pdb.yaml
    target:
      kind: PodDisruptionBudget
      name: express-api
