apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - certificate.yaml

labels:
  - pairs:
      environment: dev
    includeSelectors: false

images:
  - name: express-api
    newName: express-api
    newTag: "1.0.0"

replicas:
  - name: express-api
    count: 2

patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment
      name: express-api
