apiVersion: v1
kind: Service
metadata:
  name: express-api
  namespace: express-api
  labels:
    app: express-api
spec:
  type: ClusterIP
  selector:
    app: express-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
