apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: express-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Express API platform project
  sourceRepos:
    - __GIT_REPO_URL__
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: express-api
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: cert-manager.io
      kind: ClusterIssuer
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
