apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-api-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: express-api
    app.kubernetes.io/part-of: express-api-gitops
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: express-api
  source:
    repoURL: https://github.com/laxmanperi1/express-api.git
    targetRevision: main
    path: deploy/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: express-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
