apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - express-api-dev.yaml
  # Enable express-api-prod.yaml only on production clusters
  - express-api-prod.yaml
  - monitoring-stack.yaml
  - monitoring-config.yaml
