{
 "title": "Express API",
 "tags": [ "express-api" ],
 "panels": [
  {
   "title": "Express API CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"express-api\"}[5m]))",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Express API Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{namespace=\"express-api\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Express API Up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "up{namespace=\"express-api\", service=\"express-api\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}